extends SceneTree

var failures: Array[String] = []


func _init() -> void:
	_test_input_action()
	_test_game_settings_model()
	_test_source_wiring()
	_finish()


func _test_input_action() -> void:
	_expect(InputMap.has_action("toggle_benchmark_mode"), "InputMap should include toggle_benchmark_mode")
	var has_f4_key: bool = false
	for event in InputMap.action_get_events("toggle_benchmark_mode"):
		if event is InputEventKey:
			var key_event: InputEventKey = event as InputEventKey
			if key_event.keycode == KEY_F4 or key_event.physical_keycode == KEY_F4:
				has_f4_key = true
	_expect(has_f4_key, "toggle_benchmark_mode should be bound to F4")


func _test_game_settings_model() -> void:
	for token in ["signal graphics_changed", "func graphics_settings", "\"display_mode\"", "\"vsync\"", "\"max_fps\"", "\"resolution_scale\"", "\"scale_filter\"", "\"taa\"", "\"msaa\"", "\"fxaa\"", "\"shadow_mapping\"", "\"ssao_quality\"", "\"ssil_quality\"", "\"bloom\"", "\"volumetric_fog\"", "\"gi_quality\""]:
		_expect(_file_has("res://scripts/game_settings.gd", token), "GameSettings source should include %s" % token)


func _test_source_wiring() -> void:
	_expect(_file_has("res://scripts/game_settings.gd", "func apply_graphics_settings"), "GameSettings should apply runtime graphics settings")
	_expect(_file_has("res://scripts/game_settings.gd", "DisplayServer.window_set_vsync_mode(vsync_mode)"), "GameSettings should apply VSync")
	_expect(_file_has("res://scripts/game_settings.gd", "Engine.max_fps = max_fps"), "GameSettings should apply max_fps")
	_expect(_file_has("res://scripts/main_menu_ui.gd", "SettingsScroll"), "Settings menu should use a scrollable settings body")
	_expect(_file_has("res://scripts/main_menu_ui.gd", "settings_active_tab"), "Settings menu should track the active settings tab")
	_expect(_file_has("res://scripts/main_menu_ui.gd", "_set_settings_active_tab"), "Settings tabs should be interactive")
	_expect(_file_has("res://scripts/main_menu_ui.gd", "_build_settings_active_page"), "Settings menu should build only the active tab page")
	_expect(_file_has("res://scripts/main_menu_ui.gd", "_build_settings_video_page"), "Settings menu should isolate video settings")
	_expect(_file_has("res://scripts/main_menu_ui.gd", "_build_settings_render_page"), "Settings menu should isolate render settings")
	_expect(_file_has("res://scripts/main_menu_ui.gd", "_build_settings_gameplay_page"), "Settings menu should isolate gameplay settings")
	_expect(_file_has("res://scripts/main_menu_ui.gd", "_add_settings_option_row"), "Settings menu should include graphics option rows")
	_expect(_file_has("res://scripts/main_menu_ui.gd", "GameSettings.set_graphics_setting"), "Settings menu should write graphics options to GameSettings")
	_expect(_file_has("res://scripts/main_menu_ui.gd", "settings.resolution_scale"), "Settings menu should expose resolution scale")
	_expect(_file_has("res://scripts/main_menu_ui.gd", "settings.global_illumination"), "Settings menu should expose GI quality")
	_expect(_file_has("res://scripts/level.gd", "BENCHMARK_WINDOW_SIZE"), "Level should define benchmark window size")
	_expect(_file_has("res://scripts/level.gd", "DisplayServer.window_set_vsync_mode(DisplayServer.VSYNC_DISABLED)"), "Benchmark mode should disable VSync")
	_expect(_file_has("res://scripts/level.gd", "_sync_menu_background_performance_state"), "Level should suspend background world rendering behind menu")
	_expect(_file_has("res://scripts/level.gd", "_sync_match_performance_policy"), "Level should automatically apply the match high-FPS render policy")
	_expect(_file_has("res://scripts/level.gd", "MATCH_PERFORMANCE_MAIN_SHADOW_DISTANCE := 28.0"), "Match performance policy should cap real-time shadow distance aggressively")
	_expect(_file_has("res://scripts/level.gd", "MATCH_PERFORMANCE_DECOR_VISIBILITY_RANGE := 48.0"), "Match performance policy should cull distant nonessential decor")
	_expect(_file_has("res://scripts/level.gd", "MATCH_PERFORMANCE_HIDDEN_DECOR_NAME_TOKENS"), "Match performance policy should be able to hide known high-poly decorative meshes")
	_expect(_file_has("res://scripts/level.gd", "MATCH_PERFORMANCE_HEAVY_MAP_DECOR_VISIBILITY_RANGE := 30.0"), "Imported heavy map decor should use a tighter active-play cull range")
	_expect(_file_has("res://scripts/level.gd", "func _is_heavy_match_map_decor_geometry"), "Heavy imported map decor detection should stay centralized")
	_expect(_file_has("res://scripts/level.gd", "MATCH_PERFORMANCE_HEAVY_MAP_DECOR_NAME_TOKENS"), "Heavy imported map decor should be tokenized separately from hidden decor")
	_expect(_file_has("res://scripts/level.gd", "MATCH_PERFORMANCE_PLAYER_VISUAL_VISIBILITY_RANGE := 80.0"), "Player visuals should use a dedicated match cull range instead of decor distance")
	_expect(_file_has("res://scripts/level.gd", "\"PlayersContainer\""), "Match performance runtime policy should include spawned player visuals")
	_expect(_file_has("res://scripts/level.gd", "func _is_player_visual_geometry"), "Player visual geometry detection should stay centralized")
	_expect(_file_has("res://scripts/level.gd", "MATCH_PERFORMANCE_PLAYER_VISUAL_VISIBILITY_MARGIN"), "Player visual culling should keep its own margin")
	_expect(_file_has("res://scripts/level.gd", "fixeddecor_cozybeaver"), "Cozy Beaver should be treated as a nonessential high-poly active-play decoration")
	_expect(_file_has("res://scripts/level.gd", "tanks_light_tank"), "Light Tank decor should be treated as nonessential during active play")
	_expect(_file_has("res://scripts/level.gd", "synty_car_small"), "Small Car decor should be treated as nonessential during active play")
	_expect(_file_has("res://scripts/level.gd", "tanks_busted_tank"), "Busted Tank decor should be treated as nonessential during active play")
	_expect(_file_has("res://scripts/level.gd", "func _is_hidden_match_decor_geometry"), "Match performance policy should keep high-poly decor detection centralized")
	_expect(_file_has("res://scripts/level.gd", "instance.visible = false"), "Hidden high-poly decor should be removed from active-play rendering")
	_expect(_file_has("res://scripts/level.gd", "\"visible\","), "Match performance policy should restore original visibility when disabled")
	_expect(_file_has("res://scripts/level.gd", "Environment.REFLECTION_SOURCE_DISABLED"), "Match performance policy should disable expensive sky reflections")
	_expect(_file_has("res://scripts/level.gd", "GeometryInstance3D.SHADOW_CASTING_SETTING_OFF"), "Match performance policy should disable nonessential decor shadows")
	_expect(_file_has("res://scripts/level.gd", "_is_main_match_shadow_light"), "Match performance policy should keep only the authored main directional shadow")
	_expect(_file_has("res://scripts/level.gd", "_find_light_nodes"), "Match and benchmark light policies should recursively collect Light3D subclasses")
	_expect(_file_has("res://scripts/level.gd", "node is Light3D"), "Light policies should not miss DirectionalLight3D children imported from map scenes")
	_expect(_file_has("res://scripts/level.gd", "light.get_parent() == environment_root"), "Nested imported directional lights should not keep real-time shadows during active play")
	_expect(_file_has("res://scripts/level.gd", "_is_runtime_map_prop_geometry"), "Match performance policy should include runtime map props without culling true map geometry")
	_expect(_file_has("res://scripts/level.gd", "var object_value: Variant = state.get(\"node\", null)"), "Match performance policy should ignore freed runtime nodes when refreshing cached render state")
	_expect(_file_has("res://scripts/level.gd", "PARTY_MONSTER_ACCESSORY_MAX_PICKUPS := 24"), "Party Monster accessory pickups should stay capped during active play")
	_expect(_file_has("res://scripts/level.gd", "total_players + 18"), "Party Monster accessory pickup count should scale gently with player count")
	_expect(_file_has("res://scripts/level.gd", "_request_match_performance_policy_refresh"), "Runtime-spawned match objects should refresh the active performance policy")
	_expect(_file_has("res://scripts/level.gd", "_apply_match_performance_runtime_node_policy"), "Runtime-spawned match objects should use incremental render-policy refresh")
	_expect(_file_has("res://scripts/unity_asset_catalog.gd", "ACTIVE_PLAY_EXCLUDED_DECOR_IDS"), "Unity decor catalog should exclude high-poly decoration from active-play random spawns")
	_expect(_file_has("res://scripts/unity_asset_catalog.gd", "func random_active_play_decoration"), "Unity decor catalog should expose an active-play-safe random decoration pool")
	_expect(_file_has("res://scripts/level.gd", "UnityAssetCatalog.random_active_play_decoration(rng)"), "Level should spawn active-play-safe Unity decorations")
	_expect(_file_has("res://scripts/level.gd", "_server_spawn_match_pickups_for_round()"), "Match pickups should be pre-spawned during prep instead of at PLAY start")
	_expect(_file_has("res://scripts/level.gd", "_set_match_pickups_active(false)"), "Prep-time match pickups should stay inactive until hunting starts")
	_expect(_file_has("res://scripts/level.gd", "_set_match_pickups_active(true)"), "PLAY start should activate pre-spawned match pickups without respawning them")
	_expect(_file_has("res://scripts/level.gd", "_rpc_set_match_pickups_active"), "Match pickup active state should replicate without rebuilding spawned nodes")
	_expect(_file_has("res://scripts/level.gd", "MATCH_PICKUP_ACTIVATION_BATCH_SIZE := 2"), "PLAY start should stagger pickup activation across many small frame batches")
	_expect(_file_has("res://scripts/level.gd", "_match_pickup_activation_active = not _match_pickup_activation_queue.is_empty()"), "PLAY start should not activate the first pickup batch in the same transition frame")
	_expect(_file_has("res://scripts/level.gd", "_match_pickup_activation_queue = _collect_match_pickups()"), "Pickup activation should use a queued batch to avoid hunt-start frame spikes")
	_expect(_file_has("res://scripts/level.gd", "while processed < budget and not _match_pickup_activation_queue.is_empty()"), "Pickup activation queue should be bounded by a per-frame batch budget")
	_expect(_file_has("res://scripts/level.gd", "_match_pickup_activation_queue.pop_front()"), "Pickup activation queue should drain incrementally instead of toggling all pickups at once")
	_expect(_file_has("res://scripts/level.gd", "_process_match_pickup_activation_queue()"), "Level process should drain the pickup activation queue over several frames")
	_expect(_file_has("res://scripts/level.gd", "preparation_room.process_mode = Node.PROCESS_MODE_DISABLED"), "Hidden preparation-room content should stop processing during active play")
	_expect(_file_has("res://scripts/level.gd", "_sync_active_match_training_targets()"), "Active play should suspend training-only targets")
	_expect(_file_has("res://scripts/level.gd", "training_targets.process_mode = Node.PROCESS_MODE_DISABLED"), "Training-only targets should stop processing during active play")
	_expect(_file_has("res://scripts/level.gd", "animation_player.active = active"), "Training-only target animations should pause during active play")
	_expect(_file_has("res://scripts/level.gd", "game_state == GameState.PLAY"), "Match performance policy should apply during active play")
	_expect(_file_has("res://scripts/level.gd", "_apply_match_performance_render_policy(false)"), "Benchmark mode should restore the automatic match policy safely")
	_expect(_file_has("res://scripts/party_monster_accessory_pickup.gd", "VISUAL_UPDATE_INTERVAL := 1.0 / 30.0"), "Party Monster accessory pickups should throttle active visual updates")
	_expect(_file_has("res://scripts/party_monster_accessory_pickup.gd", "IDLE_VISUAL_UPDATE_INTERVAL := 1.0 / 12.0"), "Far accessory pickups should use lower-frequency idle visual updates")
	_expect(_file_has("res://scripts/party_monster_accessory_pickup.gd", "BEACON_IDLE_REFRESH_INTERVAL := 0.42"), "Far accessory pickups should not scan beacon visibility every active frame window")
	_expect(_file_has("res://scripts/party_monster_accessory_pickup.gd", "_seed_process_stagger"), "Accessory pickup update timers should be staggered after batch spawn")
	_expect(_file_has("res://scripts/party_monster_accessory_pickup.gd", "set_process(_should_process_pickup())"), "Unavailable accessory pickups should stop client-side idle processing")
	_expect(_file_has("res://scripts/party_monster_accessory_pickup.gd", "return _is_local_player_nearby() or _is_bounty_beacon_visible()"), "Available accessory pickups should process only near the local player or active bounty beacon")
	_expect(_file_has("res://scripts/party_monster_accessory_pickup.gd", "PREVIEW_VISIBILITY_RANGE := 28.0"), "Accessory pickup previews should have a local cull range")
	_expect(_file_has("res://scripts/level.gd", "MATCH_PERFORMANCE_PICKUP_VISIBILITY_RANGE := 26.0"), "Match performance policy should keep pickup visuals on a shorter cull range than decor")
	_expect(_file_has("res://scripts/level.gd", "MATCH_PERFORMANCE_PICKUP_LABEL_VISIBILITY_RANGE := 18.0"), "Pickup labels should cull before mesh previews")
	_expect(_file_has("res://scripts/level.gd", "func _is_match_pickup_geometry"), "Pickup geometry should have a dedicated match-performance classifier")
	_expect(_file_has("res://scripts/level.gd", "func _is_bounty_beacon_geometry"), "Bounty beacon geometry should be classified separately from ordinary pickup previews")
	_expect(_file_has("res://scripts/party_monster_accessory_pickup.gd", "BEACON_PULSE_INTERVAL := 1.0 / 30.0"), "Party Monster accessory beacon animation should be capped")
	_expect(_file_has("res://scripts/party_monster_accessory_pickup.gd", "sphere.radial_segments = 12"), "Party Monster accessory fallback previews should use low-poly sphere meshes")
	_expect(_file_has("res://scripts/party_monster_accessory_pickup.gd", "mesh.radial_segments = 18"), "Party Monster accessory beacon impact discs should stay low-poly")
	_expect(_file_has("res://scripts/party_monster_accessory_pickup.gd", "set_process_unhandled_input(local_nearby)"), "Accessory pickups should only listen for input while the local player is nearby")
	_expect(_file_has("res://scripts/ammo_pickup.gd", "match_active and is_available"), "Ammo pickups should be hidden and non-colliding before active play")
	_expect(_file_has("res://scripts/ammo_pickup.gd", "set_process(match_active and _is_runtime_server() and not is_available)"), "Ammo pickups should process only while active and waiting for server respawn")
	_expect(_file_has("res://scripts/level.gd", "_make_runtime_ammo_mesh"), "Active-play ammo pickups should use lightweight runtime meshes")
	_expect(_file_lacks("res://scripts/level.gd", "AmmoPickup.visual_scene_path_for_type(type)"), "Active-play ammo pickups should not instantiate high-poly GLB visuals")
	_expect(_file_has("res://scripts/fruit_prop.gd", "NETWORK_SYNC_INTERVAL := 0.16"), "Map props should use a lower-priority movement sync interval")
	_expect(_file_has("res://scripts/fruit_prop.gd", "set_physics_process(authoritative_body and not sleeping)"), "Resting map props should not run their own physics process")
	_expect(_file_has("res://scripts/fruit_prop.gd", "freeze = sleeping"), "Authoritative resting map props should freeze while idle")
	_expect(_file_has("res://scripts/fruit_prop.gd", "set_physics_process(false)"), "Authoritative resting map props should stop processing after they settle")
	_expect(_file_has("res://scripts/fruit_prop.gd", "func _wake_authoritative_body"), "Map prop impacts should unfreeze authoritative bodies before movement")
	_expect(_file_has("res://scripts/fruit_prop.gd", "CONTACT_REPORT_COUNT := 2"), "Resting map props should keep contact reporting disabled until impact wakes them")
	_expect(_file_has("res://scripts/fruit_prop.gd", "_set_contact_reporting(false)"), "Resting and remote map props should not keep contact reporting enabled")
	_expect(_file_lacks("res://scripts/level.gd", "(prop as RigidBody3D).sleeping = false"), "Gravity changes should not wake every spawned disguise prop at match start")
	_expect(_file_has("res://scripts/fruit_prop.gd", "RUNTIME_VISUAL_CULL_RANGE := 28.0"), "Runtime map prop visuals should use a tighter active-play cull range")
	_expect(_file_has("res://scripts/fruit_prop.gd", "func _load_cached_packed_scene"), "Runtime map prop spawning should reuse cached prop PackedScenes")
	_expect(_file_has("res://scripts/fruit_prop.gd", "func _apply_static_visual_subtree_policy"), "Runtime map prop visual subtrees should not keep imported scripts or animations processing")
	_expect(_file_has("res://scripts/fruit_prop.gd", "FORCE_REST_DELAY := 0.24"), "Low-motion map props should settle quickly after impact")
	_expect(_file_has("res://scripts/fruit_prop.gd", "func _apply_runtime_visual_policy"), "Runtime map prop visuals should disable expensive mesh features at spawn time")
	_expect(_file_has("res://scripts/fruit_prop.gd", "REMOTE_VISUAL_SMOOTH_SPEED := 18.0"), "Remote map prop movement should smooth its visual layer without extra physics")
	_expect(_file_has("res://scripts/level.gd", "MATCH_PERFORMANCE_RUNTIME_PROP_VISIBILITY_RANGE := 28.0"), "Match performance policy should not widen runtime map-prop culling back to decor range")
	_expect(_file_has("res://scripts/level.gd", "MAP_PROP_MOTION_SYNC_RELEVANCE_RADIUS: float = 20.0"), "Moving map prop states should replicate only to nearby relevant peers")
	_expect(_file_has("res://scripts/level.gd", "func _map_prop_motion_payload_for_peer"), "Moving map prop states should be filtered per recipient")
	_expect(_file_has("res://scripts/level.gd", "_rpc_sync_map_prop_motion_states.rpc_id(peer_id, peer_payload)"), "Moving map prop batches should send per-peer payloads")
	_expect(_file_has("res://scripts/player.gd", "PROP_PUSH_QUERY_MAX_RESULTS := 8"), "Player map-prop push assist should cap nearby physics query results")
	_expect(_file_has("res://scripts/player.gd", "space_state.intersect_shape(query, PROP_PUSH_QUERY_MAX_RESULTS)"), "Player map-prop push assist should query nearby physics bodies")
	_expect(_file_has("res://scripts/player.gd", "PROP_PUSH_QUERY_INTERVAL_MSEC := 50"), "Player map-prop push assist should be throttled instead of running every physics frame")
	_expect(_file_has("res://scripts/player.gd", "PROP_PUSH_ASSIST_MIN_SPEED := 2.6"), "Player map-prop push assist should only run during meaningful movement")
	_expect(_file_lacks("res://scripts/player.gd", "get_tree().get_nodes_in_group(\"map_props\")"), "Player map-prop push assist should not scan every spawned prop each physics frame")
	_expect(_file_has("res://scripts/map_prop_sync_budget.gd", "DEFAULT_MOTION_FLUSH_INTERVAL: float = 1.0 / 8.0"), "Map prop motion sync should stay below player-critical update cadence")
	_expect(_file_has("res://scripts/map_prop_sync_budget.gd", "DEFAULT_MAX_MOTION_STATES_PER_FLUSH: int = 4"), "Map prop sync budget should cap active motion bursts")
	_expect(_file_has("res://scripts/map_prop_sync_budget.gd", "DEFAULT_MAX_REST_STATES_PER_FLUSH: int = 8"), "Map prop reliable rest sync should avoid large PLAY-frame bursts")
	_expect(_file_has("res://scripts/level.gd", "MAP_PROP_SPAWN_BATCH_SIZE: int = 2"), "Map prop spawning should be amortized across frames instead of stalling netfox rollback")
	_expect(_file_has("res://scripts/level.gd", "MAP_PROP_SPAWN_BATCH_DELAY_SECONDS: float = 1.0 / 60.0"), "Map prop spawn batches should be spread across rendered frames")
	_expect(_file_has("res://scripts/level.gd", "_schedule_map_prop_spawn_batch(generation, replicate_to_clients)"), "Map prop spawn queue should schedule follow-up batches through the frame-paced helper")
	_expect(_file_has("res://scripts/level.gd", "return role == Network.Role.NONE"), "Spectators should not receive full continuous map-prop motion streams")
	_expect(_file_has("res://scripts/level.gd", "_rpc_spawn_map_props_batch.rpc(batch"), "Map prop client spawn replication should be chunked")
	_expect(_file_lacks("res://scripts/level.gd", "_rpc_prepare_map_props_spawn.rpc()\n\t_queue_map_prop_spawn_batches(container, spawn_data, true)"), "Map prop batch spawn should prepare remote containers exactly once through the queue helper")
	_expect(_file_has("res://scripts/level.gd", "UNITY_DECOR_SPAWN_BATCH_SIZE: int = 3"), "Pure decor spawning should be amortized across frames")
	_expect(_file_has("res://scripts/level.gd", "UNITY_DECOR_SPAWN_BATCH_DELAY_SECONDS: float = 1.0 / 60.0"), "Pure decor spawn batches should be spread across rendered frames")
	_expect(_file_has("res://scripts/level.gd", "_schedule_unity_decor_spawn_batch(generation, replicate_to_clients)"), "Pure decor spawn queue should schedule follow-up batches through the frame-paced helper")
	_expect(_file_has("res://scripts/level.gd", "UNITY_DECOR_VISUAL_CULL_RANGE: float = 32.0"), "Pure decor visuals should use a bounded active-play cull range")
	_expect(_file_has("res://scripts/level.gd", "func _load_cached_unity_decor_scene"), "Pure decor spawning should reuse cached PackedScenes")
	_expect(_file_has("res://scripts/level.gd", "func _load_cached_unity_decor_material"), "Pure decor material overrides should reuse cached Materials")
	_expect(_file_has("res://scripts/level.gd", "func _apply_unity_decoration_runtime_policy"), "Pure decor visual subtrees should disable imported processing, animation, shadows, and GI")
	_expect(_file_has("res://scripts/level.gd", "_apply_unity_decoration_runtime_policy(node)"), "Pure decor runtime policy should run immediately after instantiation")
	_expect(_file_has("res://scripts/level.gd", "_rpc_spawn_unity_decorations_batch.rpc(batch"), "Pure decor client spawn replication should be chunked")
	_expect(_file_lacks("res://scripts/level.gd", "_rpc_prepare_unity_decorations_spawn.rpc()\n\t_queue_unity_decor_spawn_batches(container, spawn_data, true)"), "Unity decor batch spawn should prepare remote containers exactly once through the queue helper")
	_expect(_file_has("res://scripts/hunter_auto_turret_system.gd", "USE_HIGH_POLY_DRONE_VISUAL_DEFAULT := false"), "Auto turret should not instantiate the high-poly combat drone by default during active play")
	_expect(_file_has("res://scripts/network.gd", "\"hunter_auto_turret_enabled\": false"), "Auto turret should be opt-in instead of enabled for every Hunter by default")
	_expect(_file_has("res://scripts/hunter_auto_turret_system.gd", "get(\"hunter_auto_turret_enabled\", false)"), "Auto turret runtime should keep missing lobby config fields disabled")
	_expect(_file_has("res://scripts/player.gd", "get(\"hunter_auto_turret_enabled\", false)"), "Hunter players should only attach auto turret processing when the lobby explicitly enables it")
	_expect(_file_has("res://scripts/main_menu_ui.gd", "_option([false, true], \"auto_turret_enabled\")"), "Auto turret lobby UI should default to OFF")
	_expect(_file_has("res://scripts/hunter_auto_turret_system.gd", "TARGET_SCAN_INTERVAL := 0.22"), "Auto turret target scans should stay below high-frequency per-hunter CPU pressure")
	_expect(_file_has("res://scripts/hunter_auto_turret_system.gd", "TARGET_LOCKED_SCAN_INTERVAL := 0.36"), "Auto turret should rescan slower while a cached target remains trackable")
	_expect(_file_has("res://scripts/hunter_auto_turret_system.gd", "func _apply_turret_visual_performance_policy"), "Auto turret visual meshes should receive the active-play render budget policy")
	_expect(_file_has("res://scripts/hunter_auto_turret_system.gd", "barrel_mesh.radial_segments = 10"), "Auto turret fallback barrel should stay low-poly")
	_expect(_file_has("res://scripts/level_layout_config.gd", "MAP_PROP_COUNT_MIN: int = 24"), "2-player map prop density should stay within the active-play performance budget")
	_expect(_file_has("res://scripts/level_layout_config.gd", "MAP_PROP_COUNT_8: int = 36"), "8-player map prop density should stay within the active-play performance budget")
	_expect(_file_has("res://scripts/level_layout_config.gd", "MAP_PROP_COUNT_24: int = 56"), "24-player map prop density should keep enough hider disguise candidates")
	_expect(_file_has("res://scripts/level_layout_config.gd", "UNITY_DECOR_COUNT_24: int = 36"), "24-player pure Unity decor should stay below the hider prop budget")
	_expect(_file_has("res://scripts/level.gd", "HUD_REFRESH_INTERVAL := 0.10"), "Client HUD data assembly should be throttled instead of running at uncapped render FPS")
	_expect(_file_has("res://scripts/level.gd", "func _process_client_hud_refresh"), "Level should centralize throttled client HUD refresh")
	_expect(_file_has("res://scripts/level.gd", "_process_client_hud_refresh(delta)"), "Level _process should route HUD updates through the refresh budget")
	_expect(_file_has("res://scripts/player.gd", "func _refresh_runtime_process_policy"), "Player root should centralize runtime process policy")
	_expect(_file_has("res://scripts/player.gd", "set_process(should_process_visuals)"), "Dedicated server player roots should skip render-only frame processing")
	_expect(_file_has("res://scripts/player.gd", "set_physics_process(is_local_player)"), "Remote player roots should not be physics-process scheduled")
	_expect(_file_has("res://scripts/player.gd", "func _refresh_runtime_netfox_policy"), "Player root should centralize runtime netfox policy")
	_expect(_file_has("res://scripts/player.gd", "REMOTE_VISUAL_PROCESS_INTERVAL := 1.0 / 30.0"), "Remote player visual animation should be capped below render FPS")
	_expect(_file_has("res://scripts/player.gd", "_process_remote_visual_frame(remote_visual_delta)"), "Remote player visual frame work should run through a throttled helper")
	_expect(_file_has("res://scripts/player.gd", "empty_state_properties: Array[String]"), "Remote rollback slimming should preserve typed RollbackSynchronizer state arrays")
	_expect(_file_has("res://scripts/player.gd", "rollback_sync.call_deferred(\"_disconnect_signals\")"), "Remote rollback slimming should disconnect netfox rollback tick signals")
	_expect(_file_has("res://assets/characters/party_monster/party_monster_skin.gd", "idle_variation_process_enabled"), "Remote Party Monster idle variation processing should be switchable")
	_expect(_file_has("res://scripts/network/player_input_state.gd", "func _refresh_capture_policy"), "PlayerInputState should centralize local input capture policy")
	_expect(_file_has("res://scripts/network/player_input_state.gd", "set_process(buffer_frame_input and should_capture)"), "Remote PlayerInputState nodes should not poll local input every frame")
	_expect(_file_has("res://scripts/network/player_input_state.gd", "_disconnect_tick_capture()"), "Remote PlayerInputState nodes should disconnect from netfox input ticks")
	_expect(_file_has("res://scripts/network/player_movement_motor.gd", "func _refresh_processing_policy"), "MovementMotor should reapply process policy after exports are loaded")
	_expect(_file_has("res://scripts/network/player_movement_motor.gd", "set_physics_process(mirror_player_physics_state)"), "MovementMotor should respect mirror_player_physics_state instead of defaulting to physics processing")
	_expect(_file_has("res://scripts/spring_arm_offset.gd", "func _refresh_camera_process_policy"), "Camera rig should centralize owner-only frame processing")
	_expect(_file_has("res://scripts/spring_arm_offset.gd", "set_process(authority == multiplayer.get_unique_id())"), "Remote camera rigs should not smooth unused cameras every frame")
	_expect(_file_has("res://scripts/spring_arm_offset.gd", "not RuntimeMode.has_multiplayer_peer(multiplayer)"), "Offline camera rigs should avoid querying multiplayer authority without a peer")
	_expect(_file_has("res://scripts/network/netfox_player_transform_sync.gd", "func _refresh_processing_policy"), "Transform sync should centralize interpolation process policy")
	_expect(_file_has("res://scripts/network/netfox_player_transform_sync.gd", "should_process = not _is_owner_authority() and not _is_runtime_multiplayer_server()"), "Only client-side remote transform sync should run frame interpolation")
	_expect(_file_has("res://scripts/i18n.gd", "settings.display_mode"), "I18n should include settings display labels")
	_expect(_file_has("res://scripts/i18n.gd", "settings.section.gameplay"), "I18n should include settings gameplay section label")


func _file_has(path: String, token: String) -> bool:
	var file: FileAccess = FileAccess.open(path, FileAccess.READ)
	if file == null:
		return false
	var content: String = file.get_as_text()
	return content.contains(token)


func _file_lacks(path: String, token: String) -> bool:
	var file: FileAccess = FileAccess.open(path, FileAccess.READ)
	if file == null:
		return false
	var content: String = file.get_as_text()
	return not content.contains(token)


func _expect(condition: bool, message: String) -> void:
	if not condition:
		failures.append(message)


func _finish() -> void:
	if failures.is_empty():
		print("[PerformanceSettingsTest] PASS")
		quit(0)
		return
	for failure in failures:
		push_error("[PerformanceSettingsTest] " + failure)
	quit(1)
